CREATE TABLE public.iaqp_semillas (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    mesa_id TEXT NOT NULL,
    hash_publicado TEXT NOT NULL UNIQUE,
    semilla TEXT,
    rondas INTEGER NOT NULL DEFAULT 0 CHECK (rondas >= 0),
    abierta_en TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    revelada_en TIMESTAMPTZ,
    CHECK (char_length(hash_publicado) = 64),
    CHECK (revelada_en IS NULL OR semilla IS NOT NULL)
);

CREATE TABLE public.iaqp_rondas (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    mesa_id TEXT NOT NULL,
    juego TEXT NOT NULL,
    semilla_id BIGINT NOT NULL REFERENCES public.iaqp_semillas(id),
    nonce INTEGER NOT NULL CHECK (nonce > 0),
    semilla_cliente TEXT NOT NULL,
    estado TEXT NOT NULL CHECK (estado IN ('abierta', 'cerrada', 'resuelta', 'anulada')),
    resultado JSONB,
    apostado BIGINT NOT NULL DEFAULT 0 CHECK (apostado >= 0),
    devuelto BIGINT NOT NULL DEFAULT 0 CHECK (devuelto >= 0),
    abierta_en TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    cerrada_en TIMESTAMPTZ,
    resuelta_en TIMESTAMPTZ,
    UNIQUE (semilla_id, nonce)
);

CREATE TABLE public.iaqp_apuestas (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ronda_id BIGINT NOT NULL REFERENCES public.iaqp_rondas(id),
    jugador_id TEXT NOT NULL,
    tipo TEXT NOT NULL,
    valor JSONB,
    monto BIGINT NOT NULL CHECK (monto > 0),
    ref TEXT,
    gana BOOLEAN,
    devuelto BIGINT NOT NULL DEFAULT 0 CHECK (devuelto >= 0),
    creada_en TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    UNIQUE (ronda_id, ref)
);

CREATE TABLE public.iaqp_movimientos (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    jugador_id TEXT NOT NULL,
    ronda_id BIGINT NOT NULL REFERENCES public.iaqp_rondas(id),
    tipo TEXT NOT NULL CHECK (tipo IN ('premio', 'devolucion')),
    monto BIGINT NOT NULL CHECK (monto > 0),
    ref_externa TEXT NOT NULL UNIQUE,
    estado TEXT NOT NULL CHECK (estado IN ('pendiente', 'confirmado', 'fallido', 'trabado')),
    error TEXT,
    creado_en TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    confirmado_en TIMESTAMPTZ
);

CREATE INDEX iaqp_movimientos_pendientes_idx
    ON public.iaqp_movimientos (creado_en)
    WHERE estado <> 'confirmado';
